[tool.poetry]
name = "blind-charging-api"
version = "0.1.0"
description = ""
authors = ["Joe Nudell <jnudell@hks.harvard.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.9.5"
fastapi = "^0.111.0"
fastapi-sso = "^0.15.0"
pyjwt = "^2.8.0"
pydantic = "^2.7.1"
sqlalchemy = "^2.0.30"
pyodbc = "^5.1.0"
aioodbc = "^0.5.0"
python-glowplug = "^0.3.2"
typer = "^0.12.3"
pydantic-settings = "^2.2.1"
uuid-utils = "^0.7.0"
greenlet = "^3.0.3"
gunicorn = "^22.0.0"
uvicorn = "^0.29.0"
jinja2 = "^3.1.4"
openai = "^1.30.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
