"""add extra field for exposures

Revision ID: 036e6414c02c
Revises:
Create Date: 2024-11-11 13:29:43.239159

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "036e6414c02c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exposure",
        sa.Column(
            "extra",
            sa.String(length=4194303).with_variant(sa.NVARCHAR(length="max"), "mssql"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exposure", "extra")
    # ### end Alembic commands ###
