# type: ignore
"""add embeddings table

Revision ID: e775c3bb12d8
Revises: fb649d51498d
Create Date: 2025-03-28 13:55:56.840543

"""

from typing import Sequence, Union

import sqlalchemy as sa

import app
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e775c3bb12d8"
down_revision: Union[str, None] = "fb649d51498d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_embedding",
        sa.Column("id", app.server.db.UUID7Type(length=16), nullable=False),
        sa.Column("jurisdiction_id", sa.String(length=255), nullable=False),
        sa.Column("case_id", sa.String(length=255), nullable=False),
        sa.Column("subject_id", sa.String(length=255), nullable=True),
        sa.Column("document_id", sa.String(length=255), nullable=False),
        sa.Column(
            "embedding", app.server.db.EmbeddingType(length=32768), nullable=False
        ),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("model_vendor", sa.String(length=255), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("model_version", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_embedding")
    # ### end Alembic commands ###
